name: Admin Pull Request
description: A pull request template intended for repository administrators.
title: "Admin: <Enter Title>"
labels: []
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Provide a concise explanation of the purpose and scope of this pull request.
      placeholder: Write a brief summary...
    validations:
      required: true

  - type: textarea
    id: related_issues
    attributes:
      label: Related Issues
      description: List any related issues or pull requests. Use references such as #1, #2.
      placeholder: |
        - e.g., #1
        - e.g., #2
    validations:
      required: false

  - type: textarea
    id: changes
    attributes:
      label: Changes
      description: Describe the key changes introduced in this pull request. Use bullet points for clarity.
      placeholder: |
        - Updated ...
        - Added ...
        - Removed ...
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Optional. Add any additional information, considerations, or context for reviewers.
      placeholder: Additional notes...
    validations:
      required: false