version: 2
updates:
  # -----------------------------
  # Python（pip）依存関係の更新
  # -----------------------------
  - package-ecosystem: "uv"
    directory: "/"              # requirements.txt があるディレクトリ
    schedule:
      interval: "weekly"        # 毎週チェック
    ignore:
      - dependency-name: "torch"
      - dependency-name: "numpy"
    allow:
      - dependency-name: "Pygments"
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

